'use client';
import {useEffect,useRef,useState} from 'react';
import type {Asset,Business} from '@/lib/types';
import {api} from '@/lib/client';
import {Upload,Film,UserRound,Sparkles,Scissors,Coins,ArrowRight,Check,LoaderCircle} from 'lucide-react';
export default function ReferenceVideo({business,assets,onCreated,onAssetsChanged,notify,initial}:{business:Business;assets:Asset[];onCreated:(id:string)=>void;onAssetsChanged:()=>void;notify:(s:string)=>void;initial?:any}){
 const[mode,setMode]=useState('recreate'),[reference,setReference]=useState<any>(null),[identity,setIdentity]=useState(''),[products,setProducts]=useState<string[]>([]),[promote,setPromote]=useState(false),[custom,setCustom]=useState(false),[instructions,setInstructions]=useState(''),[start,setStart]=useState(0),[end,setEnd]=useState(14.9),[duration,setDuration]=useState(10),[rights,setRights]=useState(false),[captionStyle,setCaptionStyle]=useState('none'),[link,setLink]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[credits,setCredits]=useState<any>(null),[quote,setQuote]=useState<any>(null);const video=useRef<HTMLVideoElement>(null),requestKey=useRef('');
 useEffect(()=>{api('video-credits').then(setCredits).catch(e=>setError(e.message));requestKey.current=crypto.randomUUID()},[]);
 const images=assets.filter(a=>['image/jpeg','image/png','image/webp'].includes(a.mime)&&a.category!=='Rendered'),videos=assets.filter(a=>a.mime==='video/mp4'&&a.metadata?.reference);
 useEffect(()=>{if(!initial)return;setMode(initial.video_mode);const a=assets.find(a=>a.id===initial.reference_asset_id);if(a)setReference({...a,duration:Number(a.metadata?.duration)});setIdentity(initial.identity_asset_id);setProducts(initial.product_asset_ids||[]);setPromote(!!initial.promote_product);setInstructions(initial.instructions||'');setCustom(!!initial.instructions);setStart(initial.trim_start);setEnd(initial.trim_end);setDuration(initial.duration);setCaptionStyle(initial.caption_style||'none');setRights(!!initial.rights_confirmed)},[initial]);
 const payload=()=>({business_id:business.id,mode,reference_asset_id:reference?.id,identity_asset_id:identity,product_asset_ids:products,promote_product:promote,instructions:custom?instructions:'',trim_start:start,trim_end:end,duration,caption_style:captionStyle,rights_confirmed:rights,request_key:requestKey.current});
 const valid=!!reference&&!!identity&&rights&&end-start>=1&&end-start<=14.9+.00001&&end<=reference.duration+.01;
 useEffect(()=>{setQuote(null);requestKey.current=crypto.randomUUID()},[mode,reference?.id,identity,products,promote,custom,instructions,start,end,duration,captionStyle]);
 function choose(a:any){if(!a){setReference(null);return}const d=Number(a.duration||a.metadata?.duration||0);setReference({...a,duration:d});setStart(0);setEnd(Math.min(d,14.9));setQuote(null)}
 async function action(name:string,fn:()=>Promise<void>){setBusy(name);setError('');try{await fn()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function upload(file:File|undefined,kind:string){if(!file)return;await action('upload',async()=>{const f=new FormData();f.set('file',file);f.set('business_id',business.id);if(kind==='identity')f.set('category','Person');const r=await api(kind==='video'?'video-reference/upload':'assets','POST',f);if(kind==='video')choose(r.asset);else setIdentity(r.asset.id);onAssetsChanged();notify(kind==='video'?'Reference video ready. Choose your segment.':'Your identity photo is ready.')})}
 return <div className="reference-composer"><section className="reference-tools"><div className="reference-mode"><button className={mode==='recreate'?'active':''} onClick={()=>setMode('recreate')}><UserRound size={17}/><strong>Recreate with me</strong><small>Keep the motion. Use your photo.</small></button><button className={mode==='remix'?'active':''} onClick={()=>setMode('remix')}><Sparkles size={17}/><strong>Remix for my brand</strong><small>A new story inspired by the reference.</small></button></div>
 <h3><Film size={16}/>1. Your reference</h3><label className="btn secondary full"><Upload size={16}/>Upload reference MP4<input className="sr-only" type="file" accept="video/mp4" disabled={!!busy} onChange={e=>upload(e.target.files?.[0],'video')}/></label><small className="muted">Up to 80 MB · Trim to 14.90 seconds</small>{videos.length>0&&<label>Or use a saved reference<select value={reference?.id||''} onChange={e=>choose(videos.find(a=>a.id===e.target.value))}><option value="">Choose a video</option>{videos.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}<div className="reference-link"><input aria-label="TikTok reference link" value={link} onChange={e=>setLink(e.target.value)} placeholder="Paste a public TikTok video link"/><button className="btn secondary" disabled={!!busy||!link} onClick={()=>action('import',async()=>{const r=await api('video-reference/import','POST',{business_id:business.id,url:link});choose(r.asset);onAssetsChanged()})}>{busy==='import'?'Importing…':'Import'}</button></div>
 {reference&&<div className="reference-trim"><h3><Scissors size={16}/>Choose your segment</h3><div className="form-row"><label>Start (seconds)<input type="number" min={0} max={Math.max(0,reference.duration-1)} step="0.1" value={start} onChange={e=>setStart(+e.target.value)}/></label><label>End (seconds)<input type="number" min={start+1} max={Math.min(reference.duration,start+14.9)} step="0.1" value={end} onChange={e=>setEnd(+e.target.value)}/></label></div><input aria-label="Segment start" type="range" min={0} max={Math.max(0,reference.duration-1)} step="0.1" value={start} onChange={e=>{const n=+e.target.value;setStart(n);setEnd(Math.min(reference.duration,n+Math.min(14.9,end-start)))}}/><p>{(end-start).toFixed(2)} seconds selected · {reference.duration.toFixed(2)} seconds total</p><button className="text-btn" onClick={()=>{if(video.current){video.current.currentTime=start;video.current.play().catch(()=>{})}}}>Preview this segment</button></div>}
 <h3><UserRound size={16}/>2. Your identity photo</h3><label className="btn secondary full"><Upload size={16}/>Upload your photo<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" disabled={!!busy} onChange={e=>upload(e.target.files?.[0],'identity')}/></label><div className="reference-image-list">{images.map(a=><button key={a.id} aria-label={'Use '+a.name+' as identity'} className={identity===a.id?'selected':''} onClick={()=>setIdentity(a.id)}><img src={'/api/assets/'+a.id+'/thumbnail'} alt={a.name}/>{identity===a.id&&<Check size={15}/>}</button>)}</div>
 <h3><Sparkles size={16}/>3. Make it yours</h3><label className="check-label"><input type="checkbox" checked={custom} onChange={e=>setCustom(e.target.checked)}/>Add your own instructions</label>{custom&&<label>What should change?<textarea rows={3} value={instructions} maxLength={2000} onChange={e=>setInstructions(e.target.value)} placeholder="Your performance, message, offer, or creative direction…"/></label>}<label className="check-label"><input type="checkbox" checked={promote} onChange={e=>setPromote(e.target.checked)}/>Include my product and saved brand information</label>{promote&&<><p className="muted">Choose up to three product images. Riffi uses your verified brand details.</p><div className="reference-image-list">{images.map(a=><button key={a.id} aria-label={'Include '+a.name+' as product'} className={products.includes(a.id)?'selected':''} onClick={()=>setProducts(p=>p.includes(a.id)?p.filter(id=>id!==a.id):p.length<3?[...p,a.id]:p)}><img src={'/api/assets/'+a.id+'/thumbnail'} alt={a.name}/></button>)}</div></>}<div className="form-row"><label>Output length<select value={duration} onChange={e=>setDuration(+e.target.value)}>{[5,10,15].map(n=><option value={n} key={n}>{n===15?'14.90':n} seconds</option>)}</select></label><label>Spoken captions<select value={captionStyle} onChange={e=>setCaptionStyle(e.target.value)}><option value="none">None</option><option value="outlined">White outlined</option><option value="bold">Bold uppercase</option></select></label></div><label className="check-label"><input type="checkbox" checked={rights} onChange={e=>setRights(e.target.checked)}/>I can use this video and the people or characters in my reference photos.</label>
 {error&&<div role="alert" className="notice error">{error}</div>}<div className="reference-credit-card"><Coins size={18}/><div><strong>{credits?.available??0} video credits available</strong><small>Separate from your subscription. Charged after a successful video.</small></div></div>{credits&&!credits.provider_ready&&<div className="notice">Video rendering is being connected. Save a brief now and keep your reference, photo, and settings.</div>}{credits?.provider_ready&&!credits?.configured&&<div className="notice">Video credit pricing is being configured. Save your brief while it is finalized.</div>}{quote&&<p className="credit-quote">This video uses <strong>{quote.credits} credits</strong>. {quote.available<quote.credits?'You need more credits before generating.':'Credits are reserved while it renders.'}</p>}
 <div className="reference-actions"><button className="btn secondary" disabled={!!busy||!valid} onClick={()=>action('save',async()=>{const r=await api('video-reference/brief','POST',payload());onCreated(r.content.id);notify(r.message)})}>Save brief</button><button className="btn" disabled={!!busy||!valid||!credits?.provider_ready||!credits?.configured} onClick={()=>action('generate',async()=>{if(!quote){setQuote(await api('video-reference/quote','POST',payload()));return}if(quote.available<quote.credits)throw new Error('Buy a video credit pack before generating.');const r=await api('video-reference/generate','POST',{...payload(),expected_credits:quote.credits});onCreated(r.content.id);notify(r.message)})}>{busy?<LoaderCircle size={16} className="spin"/>:<Sparkles size={16}/>} {quote?'Generate video':'Review credit cost'}</button></div>{credits?.packs?.map((p:any)=><button key={p.id} className="text-btn" disabled={!!busy||!p.available} onClick={()=>action('checkout',async()=>{const saved=valid?await api('video-reference/brief','POST',payload()):null;const r=await api('video-credits/checkout','POST',{pack:p.id,content_id:saved?.content.id});location.href=r.url})}>{p.available?'Buy':'Coming soon ·'} {p.credits} video credits</button>)}</section>
 <aside className="reference-preview"><div className="preview-heading"><span>YOUR REFERENCE</span><span>{mode==='recreate'?'Motion → Your identity':'Reference → Original concept'}</span></div>{reference?<video ref={video} controls preload="metadata" src={'/api/assets/'+reference.id+'/file'} onTimeUpdate={()=>{if(video.current&&video.current.currentTime>=end)video.current.pause()}}/>:<div className="reference-placeholder"><Film size={44}/><h2>Your next video starts here.</h2><p>Bring a reference. Add yourself. Make it yours.</p></div>}{identity&&<div className="identity-summary"><img src={'/api/assets/'+identity+'/thumbnail'} alt="Selected identity"/><div><strong>Your creator identity</strong><small>{mode==='recreate'?'Replaces the main subject in the selected segment.':'Stars in your original brand concept.'}</small></div></div>}<div className="reference-explainer"><strong>{mode==='recreate'?'Your performance, reimagined.':'Inspired by the structure. Made for your brand.'}</strong><p>{mode==='recreate'?'Riffi transfers the reference motion to your selected identity. Review the result before posting.':'Riffi analyzes the selected scenes, writes a new concept with your brand voice, then generates without the original video pixels.'}</p><span><Check size={14}/>Private brand library</span><span><Check size={14}/>Download or schedule after review</span></div></aside></div>
}
