'use client';
import {useEffect,useRef,useState} from 'react';
import type {Slide,Business} from '@/lib/types';
import {templateColors} from '@/lib/render';
import {layoutSlide,TextBlock} from '@/lib/slide-layout';
import {loadBrandFonts} from '@/lib/brand-fonts';
export default function SlidePreview({slide,business,index=0,total=5,mini=false,selected,onSelect,onMove}:{slide:Slide;business:Business;index?:number;total?:number;mini?:boolean;selected?:string;onSelect?:(id:string)=>void;onMove?:(id:string,x:number,y:number)=>void}){
const root=useRef<HTMLDivElement>(null),drag=useRef<any>(null),[scale,setScale]=useState(0),[blocks,setBlocks]=useState<TextBlock[]>([]);const colors=templateColors(slide.template_id,business.kit);
useEffect(()=>{const el=root.current;if(!el)return;const resize=()=>setScale(el.clientWidth/1080);resize();const ro=new ResizeObserver(resize);ro.observe(el);return()=>ro.disconnect()},[]);
useEffect(()=>{let active=true;loadBrandFonts(business.kit).then(()=>{if(!active)return;const ctx=document.createElement('canvas').getContext('2d')!;setBlocks(layoutSlide(slide,ctx))});return()=>{active=false}},[slide,business.kit]);
return <div ref={root} className={'slide-preview native-slide precision-slide '+(mini?'mini':'')} style={{background:slide.background_color||colors.bg,aspectRatio:`1080/${slide.canvas.height}`,padding:0}}>
{slide.asset_id&&<img className="precision-photo" src={'/api/assets/'+slide.asset_id+'/optimized'} alt="" style={{height:slide.layout==='split'?'43%':'100%',top:slide.layout==='split'?'57%':0,objectPosition:`${slide.crop_x}% ${slide.crop_y}%`,transformOrigin:`${slide.crop_x}% ${slide.crop_y}%`,transform:`scale(${slide.image_zoom||1})`}}/>}
{slide.asset_id&&!!slide.overlay_opacity&&<div className="precision-shade" style={{background:`rgba(0,0,0,${slide.overlay_opacity})`}}/>}
<div className="precision-stage" style={{width:1080,height:slide.canvas.height,transform:`scale(${scale})`}}>{blocks.map(b=><div key={b.id} role={onSelect?'button':undefined} tabIndex={onSelect?0:undefined} aria-label={onSelect?'Edit '+(['headline','body','cta'].includes(b.id)?b.id:'added')+' text':undefined} className={'precision-text '+(selected===b.id?'selected':'')} style={{position:'absolute',left:b.x-b.width/2,top:b.y,width:b.width,height:b.height,cursor:onMove?'grab':'default',touchAction:onMove?'none':undefined,color:b.color,fontFamily:`"${b.font}",sans-serif`,fontWeight:b.weight,fontSize:b.size,lineHeight:1.18,textAlign:b.align}} onKeyDown={e=>{if(!onMove)return;const dx=e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:0,dy=e.key==='ArrowUp'?-1:e.key==='ArrowDown'?1:0;if(dx||dy){e.preventDefault();onMove(b.id,b.x/10.8+dx,b.y/slide.canvas.height*100+dy)}if(e.key==='Enter')onSelect?.(b.id)}} onPointerDown={e=>{if(!onMove)return;e.stopPropagation();onSelect?.(b.id);drag.current={id:b.id,startX:e.clientX,startY:e.clientY,x:b.x/10.8,y:b.y/slide.canvas.height*100};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const d=drag.current;if(!d||!onMove)return;onMove(b.id,Math.max(0,Math.min(100,d.x+(e.clientX-d.startX)/scale/10.8)),Math.max(0,Math.min(100,d.y+(e.clientY-d.startY)/scale/slide.canvas.height*100)))}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}>{b.lines.map((line,i)=><div key={i} style={{height:b.lineHeight,whiteSpace:'pre',letterSpacing:0,textTransform:'none'}}><span style={{display:'inline-block',background:b.style==='boxed'?b.background:undefined,color:b.color,borderRadius:12,padding:b.style==='boxed'?'0 20px':0,WebkitTextStroke:b.style==='outlined'?`${b.strokeWidth}px ${b.stroke}`:undefined,paintOrder:'stroke fill'}}>{line}</span></div>)}</div>)}
{slide.show_brand&&business.kit.logo_asset_id&&<img src={'/api/assets/'+business.kit.logo_asset_id+'/file'} alt="" style={{position:'absolute',right:80,top:60,width:75,height:75,objectFit:'contain'}}/>}{slide.show_brand&&<div style={{position:'absolute',left:80,top:60,font:'700 30px "TikTok Sans"',color:blocks[0]?.color}}>{business.name}</div>}<div style={{position:'absolute',right:100,bottom:170,font:'600 24px "TikTok Sans"',color:blocks[0]?.color,opacity:.65}}>{index+1}/{total}</div></div></div>
}
