import {renderBrandWebsite} from './brand-browser';
import {parseHTML} from 'linkedom';
import {AppError,config,one,run,uid,now,json,entitlement} from './db';
import {publicFetch,validatePublicUrl} from './security';
import {imageDimensions} from '../image-metadata';

const attrs=(node:any,key:string)=>node.getAttribute(key)||'';
const clean=(value:string)=>value.replace(/\s+/g,' ').trim();
function resolve(value:string,base:string){if(!value?.trim())return null;try{return validatePublicUrl(new URL(value,base).href).href}catch{return null}}
export async function boundedBytes(response:Response,max:number){if(Number(response.headers.get('content-length'))>max)throw new AppError('Website resource is too large.');const reader=response.body?.getReader();if(!reader)return new Uint8Array();const chunks:Uint8Array[]=[];let size=0;while(true){const p=await reader.read();if(p.done)break;size+=p.value.length;if(size>max){await reader.cancel();throw new AppError('Website resource is too large.')}chunks.push(p.value)}const out=new Uint8Array(size);let offset=0;for(const p of chunks){out.set(p,offset);offset+=p.length}return out}
export function colorValue(value:string):string|null{const hex=value.trim().match(/^#([a-f\d]{3}|[a-f\d]{6})$/i);if(hex)return '#'+(hex[1].length===3?hex[1].split('').map(x=>x+x).join(''):hex[1]).toLowerCase();const rgb=value.match(/^rgba?\(\s*(\d+)\s*[, ]\s*(\d+)\s*[, ]\s*(\d+)/i);if(rgb)return '#'+rgb.slice(1,4).map(x=>Math.min(255,+x).toString(16).padStart(2,'0')).join('');const hsl=value.match(/^(?:hsla?\()?\s*(\d+(?:\.\d+)?)\s*[, ]\s*(\d+(?:\.\d+)?)%\s*[, ]\s*(\d+(?:\.\d+)?)%/i);if(hsl){const h=(+hsl[1]%360)/360,s=+hsl[2]/100,l=+hsl[3]/100;const a=s*Math.min(l,1-l);const f=(n:number)=>{const k=(n+h*12)%12;return l-a*Math.max(-1,Math.min(k-3,9-k,1))};return '#'+[f(0),f(8),f(4)].map(x=>Math.round(x*255+1e-8).toString(16).padStart(2,'0')).join('')}return null}
function vivid(c:string){const rgb=[1,3,5].map(i=>parseInt(c.slice(i,i+2),16));return Math.max(...rgb)-Math.min(...rgb)>25}
export function extractStyles(css:string,themeColor=''){
 const variables=new Map<string,string>();for(const m of css.matchAll(/(--[\w-]+)\s*:\s*([^;}]+)/g))variables.set(m[1],m[2].trim());
 const candidates=new Map<string,number>();const add=(value:string,score:number)=>{const c=colorValue(value);if(c)candidates.set(c,(candidates.get(c)||0)+score)};
 if(themeColor)add(themeColor,15);
 for(const [key,value]of variables)if(/primary|brand|accent|secondary|button|action/i.test(key)&&!/(foreground|text|border)/i.test(key))add(value,/primary|brand/i.test(key)?45:25);
 for(const m of css.matchAll(/(?:background(?:-color)?|color|fill)\s*:\s*(#[\da-f]{3,8}\b|rgba?\([^)]*\)|hsla?\([^)]*\))/gi))add(m[1],2);
 const palette=[...candidates].sort((a,b)=>b[1]-a[1]).map(x=>x[0]);const brand=palette.filter(vivid);const primary=brand[0]||palette.find(c=>!['#ffffff','#000000'].includes(c));
 const fontNames:string[]=[];for(const m of css.matchAll(/font-family\s*:\s*([^;}]+)/gi)){let value=m[1];value=value.replace(/var\((--[\w-]+)(?:,[^)]*)?\)/g,(_,k)=>variables.get(k)||'');const font=value.split(',')[0].replace(/["']/g,'').trim();if(/^[\w -]{2,60}$/.test(font)&&!['inherit','sans-serif','serif','monospace','system-ui','Arial'].includes(font)&&!fontNames.includes(font))fontNames.push(font)}
 const selectorFont=(pattern:RegExp)=>{for(const rule of css.matchAll(/([^{}]+)\{([^{}]+)\}/g)){if(!pattern.test(rule[1]))continue;const declaration=rule[2].match(/font-family\s*:\s*([^;}]+)/i);if(declaration){const value=declaration[1].replace(/var\((--[\w-]+)(?:,[^)]*)?\)/g,(_,k)=>variables.get(k)||'').split(',')[0].replace(/["']/g,'').trim();if(/^[\w -]{2,60}$/.test(value))return value}}};
 const heading=selectorFont(/(?:^|[,\s])h[123](?:[,\s.:#]|$)|heading|headline/i)||fontNames[0];const body=selectorFont(/(?:^|[,\s])(?:body|html)(?:[,\s.:#]|$)/i)||heading;
 return {palette:palette.slice(0,8),primary_color:primary,accent_color:brand[1]||primary,fonts:[...new Set([heading,body,...fontNames].filter(Boolean))].slice(0,4),heading_font:heading,body_font:body};
}
export function extractWebsite(html:string,url:string){
 const{document}=parseHTML(html);const base=resolve(document.querySelector('base[href]')?.getAttribute('href')||url,url)||url;
 const meta=(name:string)=>document.querySelector(`meta[property="${name}"],meta[name="${name}"]`)?.getAttribute('content')||'';
 const title=clean(document.querySelector('title')?.textContent||'');const description=clean(meta('og:description')||meta('description'));
 const logos:{url?:string;svg?:string;name:string;score:number}[]=[];const images:{url:string;name:string;score:number}[]=[];
 for(const script of document.querySelectorAll('script[type="application/ld+json"]')){try{const data=JSON.parse(script.textContent||'{}');const visit=(v:any)=>{if(!v||typeof v!=='object')return;const logo=typeof v.logo==='string'?v.logo:v.logo?.url;if(logo){const u=resolve(logo,base);if(u)logos.push({url:u,name:'Brand logo',score:95})}if(Array.isArray(v))v.forEach(visit);if(v['@graph'])visit(v['@graph'])};visit(data)}catch{}}
 for(const node of document.querySelectorAll('img')){const src=attrs(node,'src')||attrs(node,'data-src')||attrs(node,'data-lazy-src')||attrs(node,'srcset').split(',')[0]?.trim().split(' ')[0];const u=resolve(src,base);if(!u||!src)continue;const label=clean(attrs(node,'alt')||attrs(node,'aria-label'));const signature=label+' '+src+' '+attrs(node,'class');const isLogo=/logo|wordmark|brandmark/i.test(signature);if(isLogo)logos.push({url:u,name:label||'Brand logo',score:90+(node.closest('header,nav')?10:0)});else if(!/icon|avatar|tracking|pixel|badge/i.test(signature)){images.push({url:u,name:label||'Website image',score:(node.closest('main')?10:0)+(/hero|product|screenshot|feature|app|phone/i.test(signature)?20:0)})}}
 for(const svg of document.querySelectorAll('header svg,nav svg,a[href="/"] svg')){if(/logo|brand/i.test(attrs(svg,'aria-label')+' '+attrs(svg,'class')+' '+svg.parentElement?.outerHTML.slice(0,180))&&svg.outerHTML.length<100000)logos.push({svg:svg.outerHTML,name:'Brand logo',score:80})}
 const og=resolve(meta('og:image'),base);if(og)images.push({url:og,name:'Website cover image',score:35});
 for(const node of document.querySelectorAll('link[rel]')){const rel=attrs(node,'rel');if(/icon/i.test(rel)){const u=resolve(attrs(node,'href'),base);if(u)logos.push({url:u,name:'Brand icon',score:/apple/.test(rel)?45:35})}}
 const styles=Array.from(document.querySelectorAll('style')).map(n=>n.textContent||'').join('\n');const inline=Array.from(document.querySelectorAll('[style]')).map(n=>attrs(n,'style')).join(';');
 const stylesheets=Array.from(document.querySelectorAll('link[rel="stylesheet"]')).map(n=>resolve(attrs(n,'href'),base)).filter(Boolean) as string[];
 const headings=Array.from(document.querySelectorAll('h1,h2,h3')).map(n=>clean(n.textContent||'')).filter(Boolean).slice(0,16);
 const cta=Array.from(document.querySelectorAll('main a,main button,header a')).map(n=>clean(n.textContent||'')).find(t=>/^(get started|start|try|shop|book|download|join|sign up|create|explore)/i.test(t)&&t.length<90)||'';
 document.querySelectorAll('script,style,nav,footer').forEach(n=>n.remove());const content=clean(document.body?.textContent||document.documentElement?.textContent||'').slice(0,18000);
 return {title,description,name:meta('og:site_name')||title.split(/[|—]/)[0].trim(),logos:logos.sort((a,b)=>b.score-a.score),images:[...new Map(images.sort((a,b)=>b.score-a.score).map(x=>[x.url,x])).values()].slice(0,12),styles:styles+'\n'+inline,stylesheets:stylesheets.slice(0,6),theme:meta('theme-color'),headings,cta,content,base};
}
function safeSVG(source:string){const{document}=parseHTML(source);const svg=document.querySelector('svg');if(!svg)throw new Error('Invalid SVG');const allowed=new Set(['svg','g','path','circle','ellipse','rect','line','polyline','polygon','defs','clippath','mask','lineargradient','radialgradient','stop','title','desc']);for(const n of Array.from(svg.querySelectorAll('*'))){if(!allowed.has(n.localName.toLowerCase()))n.remove()}
 for(const n of [svg,...Array.from(svg.querySelectorAll('*'))])for(const a of Array.from(n.attributes)){if(a.name.startsWith('on')||/href|style|src/i.test(a.name)||/url\((?!\s*#)/i.test(a.value))n.removeAttribute(a.name)}svg.setAttribute('xmlns','http://www.w3.org/2000/svg');return new TextEncoder().encode(svg.outerHTML)}
async function saveImported(business:any,workspace:any,sourceUrl:string,name:string,category:string,bytes:Uint8Array,mime:string,dimensions:any={}){const existing=await one('SELECT id FROM assets WHERE business_id=? AND source=? AND json_extract(metadata,\'$.source_url\')=?',business.id,'website',sourceUrl);if(existing)return existing.id;const used=await one('SELECT COALESCE(SUM(a.size),0) n FROM assets a JOIN businesses b ON b.id=a.business_id WHERE b.workspace_id=?',workspace.id);if(used.n+bytes.length>await entitlement(workspace,'storage.max'))throw new Error('Storage allowance reached.');const id=uid(),path=`private/businesses/${business.id}/assets/${id}`;await config().BUCKET.put(path,bytes,{httpMetadata:{contentType:mime}});await run('INSERT INTO assets (id,business_id,name,category,mime,path,size,source,metadata,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)',id,business.id,name.slice(0,180),category,mime,path,bytes.length,'website',json({...dimensions,source_url:sourceUrl,imported_at:now()}),now());return id}
export async function importWebsite(business:any,workspace:any,render=renderBrandWebsite){
 const warnings:string[]=[];let html='',directError='';let rendered:Awaited<ReturnType<typeof renderBrandWebsite>>|null=null;
 try{const response=await publicFetch(business.website);if(!response.ok)throw new Error(`Website returned HTTP ${response.status}.`);if(!response.headers.get('content-type')?.includes('text/html'))throw new Error('Website did not return an HTML page.');html=new TextDecoder().decode(await boundedBytes(response,1500000))}catch(e){directError=e instanceof Error?e.message:'Website request failed.'}
 let extracted=extractWebsite(html||'<html><head></head><body></body></html>',business.website);const initial=extractStyles(extracted.styles,extracted.theme);
 if(config().BROWSER&&(!html||!extracted.logos.length||!extracted.images.length||!initial.primary_color||!initial.heading_font)){
  try{rendered=await render(config().BROWSER,business.website);const live=extractWebsite(rendered.html,rendered.url);extracted={...live,logos:[...live.logos,...extracted.logos],images:[...new Map([...live.images,...extracted.images].map(i=>[i.url,i])).values()].slice(0,12),styles:extracted.styles+'\n'+live.styles+'\n'+rendered.css};html=rendered.html}catch(e){warnings.push('Browser extraction was unavailable: '+(e instanceof Error?e.message:'please retry.'))}
 }
 if(!html)throw new AppError('The website could not be loaded. '+directError+(warnings.length?' '+warnings.join(' '):'')+' Try again or add the missing brand details manually.');
 const cssSources=[{css:extracted.styles,url:extracted.base}];await Promise.all(extracted.stylesheets.map(async url=>{try{const r=await publicFetch(url);if(r.ok){const css=new TextDecoder().decode(await boundedBytes(r,400000));cssSources.push({css,url})}}catch{warnings.push('One stylesheet was unavailable.')}}));
 // Follow a small, bounded set of CSS imports (e.g. Google Fonts), never JavaScript.
 const imports=cssSources.flatMap(s=>Array.from(s.css.matchAll(/@import\s+(?:url\()?['"]([^'"]+)['"]/g)).map(m=>resolve(m[1],s.url))).filter(Boolean).slice(0,3) as string[];
 await Promise.all(imports.map(async url=>{try{const r=await publicFetch(url);if(r.ok)cssSources.push({url,css:new TextDecoder().decode(await boundedBytes(r,300000))})}catch{}}));
 const styles=extractStyles(cssSources.map(s=>s.css).join('\n'),extracted.theme);const kit:any={color_palette:styles.palette,imported_from:business.website,imported_at:now(),import_method:rendered?'browser':'direct'};if(styles.primary_color)kit.primary_color=styles.primary_color;if(styles.accent_color)kit.accent_color=styles.accent_color;if(styles.heading_font){kit.heading_font=styles.heading_font;kit.body_font=styles.body_font}
 const assets:string[]=[];if(config().BUCKET){
 const storeImage=async(candidate:any,category:string)=>{try{let bytes:Uint8Array,mime:string;if(candidate.svg){bytes=safeSVG(candidate.svg);mime='image/svg+xml'}else{const captured=rendered?.resources.get(candidate.url);if(captured){mime=captured.mime;bytes=captured.bytes}else{const r=await publicFetch(candidate.url);if(!r.ok)return null;mime=(r.headers.get('content-type')||'').split(';')[0];bytes=await boundedBytes(r,8000000);}if(mime==='image/svg+xml')bytes=safeSVG(new TextDecoder().decode(bytes))}let dimensions:any={};if(mime!=='image/svg+xml'){if(!['image/png','image/jpeg','image/webp'].includes(mime!))return null;dimensions=imageDimensions(bytes!,mime!);if(category!=='Logo'&&(dimensions.width<300||dimensions.height<200))return null}return await saveImported(business,workspace,candidate.url||business.website+'#inline-logo',candidate.name,category,bytes!,mime!,dimensions)}catch{return null}};
 for(const logo of extracted.logos.slice(0,5)){const id=await storeImage(logo,'Logo');if(id){kit.logo_asset_id=id;break}}
 for(const image of extracted.images.slice(0,8)){const id=await storeImage(image,/screenshot|screen|app preview/i.test(image.name)?'Screenshot':'Website');if(id&&!assets.includes(id))assets.push(id)}
 const faces:any[]=[];for(const source of cssSources){for(const match of source.css.matchAll(/@font-face\s*\{([^}]+)\}/gi)){const block=match[1];if(/unicode-range/i.test(block)&&!/(U\+0000-00FF|U\+0-FF)/i.test(block))continue;const name=block.match(/font-family\s*:\s*([^;]+)/i)?.[1].replace(/["']/g,'').trim();if(!name||!styles.fonts.includes(name)||faces.some(f=>f.name===name))continue;const src=block.match(/url\(['"]?([^'"\)]+)['"]?\)/i)?.[1];const url=src&&resolve(src,source.url);if(!url)continue;try{const r=await publicFetch(url);if(!r.ok)continue;const bytes=await boundedBytes(r,2000000);const magic=String.fromCharCode(...bytes.slice(0,4));const ttf=bytes[0]===0&&bytes[1]===1&&bytes[2]===0&&bytes[3]===0;if(!['wOF2','wOFF','OTTO'].includes(magic)&&!ttf)continue;const mime=magic==='wOF2'?'font/woff2':magic==='wOFF'?'font/woff':ttf?'font/ttf':'font/otf';const id=await saveImported(business,workspace,url,name,'BrandFont',bytes,mime);faces.push({name,asset_id:id,weight:clean(block.match(/font-weight\s*:\s*([^;]+)/i)?.[1]||'400'),style:clean(block.match(/font-style\s*:\s*([^;]+)/i)?.[1]||'normal')})}catch{}}}kit.font_faces=faces;
 }
 const missing=[];if(!kit.logo_asset_id)missing.push('logo');if(!kit.primary_color)missing.push('colors');if(!kit.heading_font)missing.push('font');if(!assets.length)missing.push('photos');kit.import_status=missing.length?'partial':'complete';kit.import_missing=missing;
 return {extracted,kit,asset_ids:assets,warnings,missing};
}
