import {AppError,config,one,run,uid,now,database,stmt,audit,seedConfiguration} from './db';
const enc=new TextEncoder();export const hex=(a:ArrayBuffer)=>Array.from(new Uint8Array(a)).map(x=>x.toString(16).padStart(2,'0')).join('');
export async function hash(s:string){return hex(await crypto.subtle.digest('SHA-256',enc.encode(s)))}
export function safeEqual(a:string,b:string){let diff=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)diff|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return diff===0}
export async function passwordHash(password:string,salt=hex(crypto.getRandomValues(new Uint8Array(16)).buffer)){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:enc.encode(salt),iterations:100000},key,256);return salt+':'+hex(bits)}
export async function passwordMatch(password:string,stored:string){return stored&&safeEqual(await passwordHash(password,stored.split(':')[0]),stored)}
export function cookieValue(req:Request,key:string){const part=(req.headers.get('cookie')||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(key+'='));return part?.slice(key.length+1)}
export async function currentUser(req:Request){const token=cookieValue(req,'cp_session');if(token){const u=await one('SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.id=? AND s.expires_at>? AND u.status=?',await hash(token),now(),'active');if(u)return u}return null}
export async function requireUser(req:Request){const u=await currentUser(req);if(!u)throw new AppError('Please sign in to continue.',401);return u}
export function publicUser(u:any){if(!u)return null;const{password_hash,platform_id,...result}=u;return result}
export async function sessionCookie(req:Request,userId:string){const token=uid()+uid();await run('INSERT INTO sessions (id,user_id,expires_at) VALUES (?,?,?)',await hash(token),userId,new Date(Date.now()+30*86400000).toISOString());return `cp_session=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000${new URL(req.url).protocol==='https:'?'; Secure':''}`}
export function clearCookie(req:Request){return `cp_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0${new URL(req.url).protocol==='https:'?'; Secure':''}`}
export async function createAccount(data:any,platformId:string|null=null){await seedConfiguration();const id=uid(),wid=uid(),date=now();await database().batch([stmt('INSERT INTO users (id,first_name,last_name,email,password_hash,platform_id,timezone,verified,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)',id,data.first_name,data.last_name,data.email,data.password?await passwordHash(data.password):null,platformId,data.timezone||'America/Los_Angeles',platformId?1:0,'active',date),stmt('INSERT INTO workspaces (id,owner_id,name,plan_id,subscription_status,created_at) VALUES (?,?,?,?,?,?)',wid,id,`${data.first_name}’s workspace`,'trial','trial',date),stmt('INSERT INTO workspace_members (id,workspace_id,user_id,role) VALUES (?,?,?,?)',uid(),wid,id,'owner')]);await audit(id,'account.created');return one('SELECT * FROM users WHERE id=?',id)}
export function checkOrigin(req:Request){if(['GET','HEAD'].includes(req.method))return;const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)throw new AppError('This request could not be verified. Refresh and retry.',403);if(req.headers.get('sec-fetch-site')==='cross-site')throw new AppError('Cross-site request rejected.',403)}
export async function rateLimit(req:Request,scope:string,limit=30){const key=scope+':'+(req.headers.get('cf-connecting-ip')||'local')+':'+Math.floor(Date.now()/60000);const r=await one('INSERT INTO rate_limits (id,count,expires_at) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count',key,new Date(Date.now()+120000).toISOString());if(r.count>limit)throw new AppError('Too many requests. Please wait a minute and try again.',429)}
export async function encrypt(value:string){if(!config().TOKEN_ENCRYPTION_KEY)throw new AppError('Secure social token storage is not configured.',503);const key=await crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',enc.encode(config().TOKEN_ENCRYPTION_KEY)),{name:'AES-GCM'},false,['encrypt']);const iv=crypto.getRandomValues(new Uint8Array(12));const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(value));return btoa(String.fromCharCode(...iv))+'.'+btoa(String.fromCharCode(...new Uint8Array(ciphertext)))}
export async function decrypt(value:string){const[iv,data]=value.split('.');const key=await crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',enc.encode(config().TOKEN_ENCRYPTION_KEY)),{name:'AES-GCM'},false,['decrypt']);return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:Uint8Array.from(atob(iv),c=>c.charCodeAt(0))},key,Uint8Array.from(atob(data),c=>c.charCodeAt(0))))}
export async function sendEmail(email:string,subject:string,html:string){const c=config();if(!c.MAIL_API_KEY||!c.MAIL_FROM)throw new AppError('Email delivery is not configured yet. Contact the workspace owner.',503);const res=await fetch(c.MAIL_API_URL||'https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${c.MAIL_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:c.MAIL_FROM,to:[email],subject,html})});if(!res.ok)throw new AppError('The email could not be delivered. Please retry.',502)}
export function validatePublicUrl(value:string){let u:URL;try{u=new URL(value.includes('://')?value:'https://'+value)}catch{throw new AppError('Enter a valid public website URL.')}const h=u.hostname.toLowerCase();if(u.protocol!=='https:'||u.username||u.password||u.port||!h.includes('.')||/^\d+\.\d+\.\d+\.\d+$/.test(h)||h.includes(':')||h==='localhost'||h.endsWith('.localhost')||h.endsWith('.local')||h.endsWith('.internal')||h.endsWith('.test'))throw new AppError('Use a public HTTPS website address.');return u}
export async function publicFetch(value:string){const u=validatePublicUrl(value);const res=await fetch(u.href,{redirect:'manual',signal:AbortSignal.timeout(15000),headers:{'User-Agent':'ContentPilot/1.0 brand profile analysis'}});if(res.status>=300&&res.status<400){const location=res.headers.get('location');if(!location)throw new AppError('Website redirected without a destination.');return publicFetchOnce(new URL(location,u).href)}return res}
async function publicFetchOnce(value:string){const u=validatePublicUrl(value);return fetch(u.href,{redirect:'error',signal:AbortSignal.timeout(15000)})}
