'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/client';
import {Sparkles, Layers, Globe, Check, Camera as Instagram, Play, CalendarDays, Palette, Menu, X} from 'lucide-react';
export function Logo(){return <a className="logo" href="/"><span className="logo-mark"><Layers size={21}/></span>contentpilot<span className="logo-dot">.</span></a>}
const examples=[{brand:'gift',tag:'MONEY, MADE SIMPLE',title:'Your paycheck.\nWhere did it go?',sub:'5 little habits that make a big difference.',cls:'lime',num:'01 / 05'},{brand:'slow mornings',tag:'A LITTLE DAILY RITUAL',title:'Good things\ntake a little\ntime.',sub:'Make room for your morning.',cls:'coffee',num:'01 / 04'},{brand:'studio notes',tag:'LESS BUSY. MORE IMPACT.',title:'Your next\nbig idea\nstarts here.',sub:'A better way to get things done.',cls:'pink',num:'01 / 05'},{brand:'FORM',tag:'BUILD SOMETHING BETTER',title:'Small steps.\nStronger\nyou.',sub:'Consistency is the real secret.',cls:'dark',num:'01 / 06'}];
export function ExampleCard({example,index=0}:{example:any,index?:number}){return <div className={`example ${example.cls} e${index}`}><div className="example-brand">{example.brand}<span>✳</span></div><div className="example-main"><small>{example.tag}</small><h3>{example.title}</h3><p>{example.sub}</p></div><div className="example-bottom"><span>SWIPE TO LEARN MORE</span><span>{example.num}</span></div></div>}
export default function Landing(){const[url,setUrl]=useState(''),[error,setError]=useState(''),[menu,setMenu]=useState(false),[tab,setTab]=useState('TikTok Carousels'),[plans,setPlans]=useState<any[]>([]);useEffect(()=>{api('plans').then(r=>setPlans(r.plans)).catch(()=>{})},[]);
function start(manual=false){if(!manual&&url.trim()){try{const u=new URL(url.includes('://')?url:'https://'+url);if(!['https:','http:'].includes(u.protocol)||!u.hostname.includes('.'))throw new Error();window.location.href='/signup?website='+encodeURIComponent(u.href);return}catch{setError('Enter a valid website, like yourbrand.com.');return}}window.location.href='/signup'}
return <div className="landing"><header className="marketing-nav"><Logo/><nav className={menu?'open':''}><a href="#how">How it works</a><a href="#examples">Examples</a><a href="#pricing">Pricing</a></nav><div className="nav-actions"><a href="/login">Sign in</a><button className="btn" onClick={()=>start(true)}>Get started</button><button className="icon-btn mobile-menu" aria-label="Toggle menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
<main><section className="hero"><div className="hero-label"><span/> YOUR BRAND. YOUR IDEAS. YOUR NEXT GREAT POST.</div><h1>Content worth swiping.<br/><em>Made for your brand.</em></h1><p className="hero-copy">Turn your website, products and ideas into beautiful<br className="desktop-break"/> social content. From first thought to the next swipe.</p><form className="url-form" onSubmit={e=>{e.preventDefault();start()}}><Globe size={20}/><label className="sr-only" htmlFor="website">Your website</label><input id="website" value={url} onChange={e=>setUrl(e.target.value)} placeholder="Enter your website or product URL"/><button className="btn" type="submit">Get started <Sparkles size={16}/></button></form>{error&&<p role="alert" className="error">{error}</p>}<button className="text-btn manual" onClick={()=>start(true)}>No website? Tell us about your business</button><div className="hero-proof"><Check size={15}/> Your brand, remembered <span>·</span><Check size={15}/> Every slide, connected <span>·</span><Check size={15}/> Ready when you are</div><div className="example-fan">{examples.map((example,i)=><ExampleCard key={i} example={example} index={i}/>)}</div><div className="platform-strip"><span>MADE FOR THE PLACES YOUR AUDIENCE IS</span><strong><Play size={18} fill="currentColor"/> TikTok</strong><strong><Instagram size={19}/> Instagram</strong><strong><Layers size={19}/> Carousels</strong></div></section>
<section className="section how" id="how"><div className="eyebrow">FROM IDEA TO IN FEED</div><h2>Your content workflow.<br/><em>A whole lot simpler.</em></h2><div className="steps">{[['01','Add your business','One website link. Or a few words about what you do.',Globe],['02','Make something great','Bring an idea. We’ll help turn it into a story.',Sparkles],['03','Make it yours','Fine-tune every slide, image and caption.',Palette],['04','Find your moment','Export, publish or plan your next post.',CalendarDays]].map(([n,t,d,I]:any)=><div className="step" key={n}><span className="step-number">{n}</span><I size={25}/><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section className="section example-section" id="examples"><div className="section-heading"><div><div className="eyebrow">ONE BRAND. ENDLESS POSSIBILITIES.</div><h2>A little inspiration<br/><em>for your next post.</em></h2></div><div className="tabs">{['TikTok Carousels','Instagram','Videos'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div></div>{tab==='Videos'?<div className="video-example"><Play size={35}/><h3>From your assets to a short-form story.</h3><p>Plan scenes, write a script and generate video when your video provider is connected.</p><button className="btn" onClick={()=>start(true)}>Start creating</button></div>:<div className={`examples-grid ${tab==='Instagram'?'instagram':''}`}>{examples.map((example,i)=><ExampleCard key={i} example={example}/>)}</div>}<p className="muted center">Illustrative designs. Your content starts with your own brand.</p></section>
<section className="section memory"><div><div className="eyebrow">A CREATIVE PARTNER WITH A MEMORY</div><h2>Teach it your<br/><em>brand once.</em></h2><p>Your products. Your people. Your point of view. Keep everything in one Brand Brain, so every new idea starts with what makes you, you.</p><a className="btn" href="/signup">Build your brand brain</a></div><div className="brand-visual"><div className="brand-node"><span className="logo-mark"><Layers/></span><h3>Your Brand Brain</h3><p>Everything that makes you, you.</p></div><div className="brand-tags">{['Your audience','Brand voice','Products & benefits','Colors & fonts','Photos & assets','Past content'].map(t=><span key={t}><Check size={14}/>{t}</span>)}</div></div></section>
<section className="section story-section"><div className="eyebrow">A STORY. NOT A STACK OF SLIDES.</div><h2>Every swipe has a purpose.</h2><p>Plan the complete story first. Then bring it to life, slide by slide.</p><div className="story-flow">{['The hook','The insight','The value','The next step'].map((t,i)=><div key={t}><span>0{i+1}</span><h3>{t}</h3><p>{['Stop the scroll.','Make it relatable.','Give them something useful.','Make the action feel natural.'][i]}</p></div>)}</div></section>
<section className="section pricing" id="pricing"><div className="center"><div className="eyebrow">ROOM TO GROW</div><h2>Your next chapter<br/><em>starts here.</em></h2><p>Start free. Choose a plan as your brand grows.</p></div><div className="pricing-grid">{plans.map(p=>({id:p.id,name:p.name,price:String(p.price),desc:p.description,items:[p.entitlements['businesses.max']+' business profiles',p.entitlements['carousels.monthly']+' carousels per month',p.entitlements['social_accounts.max']+' social accounts','Brand Brain & slide editor']})).map((p,i)=><div className={'price-card '+(i===1?'featured':'')} key={p.name}>{i===1&&<span className="popular">THE CREATOR’S CHOICE</span>}<h3>{p.name}</h3><p>{p.desc}</p><div className="price">${p.price}<small>/ month</small></div><a className={i===1?'btn':'btn secondary'} href={'/signup?plan='+p.id}>{i===0?'Start free':'Get started'}</a><ul>{p.items.map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul></div>)}</div></section><section className="final-cta"><Sparkles/><h2>Your next great post<br/>starts with your brand.</h2><button className="btn" onClick={()=>start()}>Let’s make something</button></section></main><footer><Logo/><p>Made for brands with something to say.</p><div><a href="#how">How it works</a><a href="#pricing">Pricing</a><a href="/login">Sign in</a><a href="/legal?tab=privacy">Privacy</a><a href="/legal?tab=terms">Terms</a></div><small>© {new Date().getFullYear()} ContentPilot</small></footer></div>}
