import type {Slide} from './types';
export const CREATIVE_STYLES=[
 {id:'photo-label',name:'Photo labels',description:'Candid photos with crisp white text labels.',mode:'photos',template:'Creator UGC',hook:'The small changes that make a big difference.',angle:'A relatable list of practical tips with a strong hook.'},
 {id:'photo-outline',name:'Creator story',description:'Full-frame photos. Bold outlined captions.',mode:'photos',template:'Creator UGC',hook:'Things I wish someone had told me sooner.',angle:'A personal, conversational story with useful takeaways.'},
 {id:'bold',name:'Big statement',description:'Oversized type. One clear point per swipe.',mode:'text',template:'Viral Bold',hook:'Your next idea deserves to be seen.',angle:'Short, punchy statements. One focused idea per slide.'},
 {id:'dark',name:'After dark',description:'Clean white typography on a dark canvas.',mode:'text',template:'Dark Tech',hook:'Stop doing more. Start doing what works.',angle:'A bold myth-versus-reality narrative with actionable advice.'},
 {id:'editorial',name:'The useful guide',description:'Calm typography and a practical step-by-step story.',mode:'text',template:'Editorial',hook:'A simple guide to getting started.',angle:'A clear educational guide with a beginning, useful steps, and a conclusion.'},
 {id:'product',name:'Product spotlight',description:'Brand photos, bold labels, and your product story.',mode:'photos',template:'Product Demo',hook:'Meet your new everyday favorite.',angle:'Show the product in context and explain real benefits without invented claims.'},
] as const;
export function creativeStyle(id:string){return CREATIVE_STYLES.find(s=>s.id===id)||CREATIVE_STYLES[0]}
export function styleSlide(slide:Slide,id:string):Slide{const style=creativeStyle(id);const photo=id.startsWith('photo')||id==='product';return {...slide,template_id:style.template,layout:'standard',align:'center',text_position:photo?'top':'middle',text_style:id==='photo-outline'?'outlined':photo?'boxed':'clean',font_family:'TikTok Sans',text_color:photo?(id==='photo-outline'?'#ffffff':'#111111'):undefined,background_color:!photo?(id==='bold'?'#f3e7dc':id==='dark'?'#202029':'#f7f4ee'):undefined,text_weight:id==='bold'?'900':'800',font_size:id==='bold'?1.05:1,show_body:id!=='bold'&&id!=='dark',show_brand:id==='product',overlay_opacity:id==='photo-outline'?.12:0,...(!photo?{asset_id:null}: {})}}
export const VIDEO_CONCEPTS=[{name:'Creator testimonial',brief:'An original fictional creator explains the real product benefits in a candid selfie-style scene. Do not invent customer testimonials.'},{name:'Product in action',brief:'Show the product being used in a realistic everyday setting, with close-up details and a concise voiceover.'},{name:'Mini explainer',brief:'Explain one useful idea through a simple visual story with an original character and clear captions.'},{name:'Behind the scenes',brief:'A natural, documentary-style look behind the business, using only verified brand facts.'}];
