import {applySlideDesign} from './slide-design';
import type {Slide} from './types';
export function requestedPoints(idea:string){const m=idea.match(/\b(\d{1,2})\s+(?:[a-z-]+\s+){0,3}(?:reasons|mistakes|tips|ways|steps|things|ideas|habits|signs|lessons|benefits|facts|myths|questions)\b/i);if(m){const n=Number(m[1]);if(n<1||n>20)throw new Error('Choose between 1 and 20 points for a readable carousel.');return n}return 5}
export function similarity(a:string,b:string){const words=(s:string)=>new Set(s.toLowerCase().replace(/[^a-z0-9 ]/g,'').split(/\s+/).filter(w=>w.length>3));const x=words(a),y=words(b);return [...x].filter(w=>y.has(w)).length/Math.max(1,new Set([...x,...y]).size)}
export function validateStory(slides:Slide[],brain:any,ctaType:string){const checks=[] as {name:string;ok:boolean;detail:string}[];const heads=slides.map(s=>s.headline.toLowerCase().trim());checks.push({name:'No repeated points',ok:new Set(heads).size===heads.length,detail:'Each slide should add a distinct idea.'});checks.push({name:'Story connected',ok:slides.length>0&&slides.every(s=>s.headline.trim()&&s.supporting_text.trim()),detail:'Each slide needs a headline and a supporting point.'});checks.push({name:'Visual style consistent',ok:new Set(slides.map(s=>s.template_id)).size<=1,detail:'Use a shared template across the carousel.'});checks.push({name:'Readable & within safe zones',ok:slides.every(s=>s.headline.length<=130&&s.supporting_text.length<=400),detail:'Keep headlines under 130 characters and body copy under 400.'});checks.push({name:'CTA ready',ok:ctaType==='None'||!!slides.at(-1)?.cta,detail:'The final slide should include the selected call to action.'});const restricted=String(brain.restricted_claims||'').split(/[,\n]/).map((s:string)=>s.trim().toLowerCase()).filter(Boolean);checks.push({name:'Brand claims checked',ok:slides.every(s=>!restricted.some((term:string)=>(s.headline+' '+s.supporting_text).toLowerCase().includes(term))),detail:'Avoid the restricted claims in your Brand Brain.'});return checks}
export function guidedPlan(idea:string,brain:any,count:number){const benefits=String(brain.benefits||'').split(/\n|;/).map((s:string)=>s.trim()).filter(Boolean);const products=String(brain.products||'').split(/\n|;/).map((s:string)=>s.trim()).filter(Boolean);const money=/paycheck|budget|spending|money|expenses/i.test(idea+' '+brain.description);const moneyPoints=[['Forgotten subscriptions','Review recurring payments. Cancel the services you no longer use.'],['Small purchases add up','Look at your recent transactions together, instead of one at a time.'],['Convenience has a cost','Compare delivery and takeout spending with your planned food budget.'],['Impulse buys change the plan','Give nonessential purchases a pause before checking out.'],['You need a clearer picture','Make time each week to see what came in, what went out and what is next.'],['Irregular expenses sneak up','Set aside room for annual bills and costs that do not happen every month.'],['Your priorities need a plan','Choose a purpose for your money before the next payday arrives.']];return Array.from({length:count},(_,i)=>money&&moneyPoints[i]?{headline:moneyPoints[i][0],supporting_text:moneyPoints[i][1]}:{headline:benefits[i]||products[i]||['Start with your audience','Make the problem clear','Focus on what matters','Make it practical','Choose your next step'][i]||`Point ${i+1}`,supporting_text:benefits[i]?`Explain how ${benefits[i].toLowerCase()} helps ${brain.audience||'your audience'}. Add a specific, verified example.`:`Add your specific point about “${idea}”. Use a real example from ${products[0]||'your business'}.`})}
export function makeSlides(points:any[],settings:any,brain:any,assetIds:string[]=[]):Slide[]{const slide=(p:any,i:number):Slide=>({id:crypto.randomUUID(),position:i+1,purpose:'List Point',headline:String(p.headline).slice(0,130),supporting_text:String(p.supporting_text).slice(0,400),asset_id:assetIds.length?assetIds[i%assetIds.length]:null,visual_source:assetIds.length?'uploaded asset':'designed graphic',visual_prompt:p.visual_prompt||'',template_id:settings.template||'Editorial',layout:'standard',cta:'',status:'ready',align:'left',font_size:1,crop_x:50,crop_y:50,canvas:{width:1080,height:settings.platform==='Instagram'?1350:1920}});const mode=settings.visual_mode|| (assetIds.length?'photos':'text');const slides=points.map((p:any,i:number)=>applySlideDesign(slide(p,i),mode));if(settings.cta_type==='Separate Slide')slides.push(applySlideDesign(slide({headline:brain.cta||'Take the next step',supporting_text:brain.positioning||brain.description||'Learn more about our business.'},slides.length),mode));if(settings.cta_type==='Separate Slide')slides[slides.length-1].purpose='CTA';if(settings.cta_type!=='None'&&slides.length)slides[slides.length-1].cta=brain.cta||'Learn more';return slides}
export function allowedContentTransition(from:string,to:string){const transitions:Record<string,string[]>={generating:['draft','failed'],draft:['ready','scheduled','archived'],ready:['draft','scheduled','archived'],scheduled:['draft','publishing','archived'],publishing:['published','failed'],published:['archived'],failed:['draft','scheduled','archived'],archived:['draft']};return from===to||transitions[from]?.includes(to)||false}
export function entitlementAllowed(limit:number,used:number,quantity=1){return Number.isFinite(limit)&&quantity>0&&used+quantity<=limit}
export function canReschedule(status:string){return ['planned','pending','failed'].includes(status)}
export function autoCaption(title:string,brain:any,style='Short'){const cta=brain.cta||'Learn more';if(style==='Engagement')return `${title}\n\nWhich point feels most familiar? Save this for later and share your take.\n\n${cta}`;if(style==='Story')return `${title}\n\nWe built ${brain.name||'our business'} for ${brain.audience||'people looking for a better way'}. Here’s a small place to start.\n\n${cta}`;return `${title}\n\nSave this for your next reset. ${cta}`}
