export const SUPPORT_EMAIL='support@riffi.com';
export const POLICY_DATE='October 2, 2026';
export type Policy = {title:string;summary:string;sections:{title:string;paragraphs:string[];items?:string[]}[]};
export const policies:Record<string,Policy>={
privacy:{title:'Privacy Policy',summary:'How Riffi handles your information while helping your brand create content and keep showing up.',sections:[
{title:'Who this policy covers',paragraphs:['Riffi operates in Canada. This policy covers Riffi’s website, accounts, creative workspace, brand imports, AI features and social publishing tools. Riffi is the service responsible for the account and service information described here. Contact support@riffi.com with privacy questions. When you upload information about other people for your business, you are responsible for having permission and providing any required notices.']},
{title:'Information we collect',paragraphs:['We collect information you provide, information needed to operate the service, and information from providers you choose to connect.'],items:['Account information: name, email, timezone, password hash for password accounts, and sign-in provider identifier for connected login methods. We do not store your password as readable text.','Brand and content information: business details, website URLs, audience, products, brand voice, colors, fonts, logos, uploaded assets, prompts, generated content, drafts, revisions and schedules.','Public website information: publicly available page text, images, logos and styling from links you submit. Some imports use a rendered browser to read public pages. This does not give Riffi access to a private website account.','Connected account information: platform, account identifier, username, connection status, profile image where supplied, publishing permissions and publication results.','Billing information: plan, subscription state, payment-provider identifiers and available invoice details. Payment card entry and processing are handled by the payment provider.','Operational information: service requests, security events, rate-limit records, timestamps, browser/network information available to our hosting providers, and messages you send to support.']},
{title:'How we use information',paragraphs:['We use information to create and secure accounts; import and remember branding; generate and edit requested content; store your workspace; schedule and publish posts you authorize; confirm publication results; administer subscriptions where available; answer support requests; and investigate errors, fraud or misuse. We do not promise audience growth or use your unpublished drafts as public examples without permission.']},
{title:'AI generation and service providers',paragraphs:['When you request AI features, relevant prompts, brand context and selected assets are sent to the configured AI provider, including OpenAI. Outputs may contain errors or resemble other outputs. Avoid including sensitive personal information that is unnecessary for the task. AI providers have their own processing and retention terms.','Cloudflare provides hosting, database, file storage and browser rendering. Post for Me manages social connections and publication requests. Google processes Google sign-in when configured. Stripe processes payments when enabled. An email delivery provider may handle requested account messages when email delivery is configured. Only features you use and providers enabled for those features receive the relevant information.'],items:['OpenAI privacy information: https://openai.com/policies/privacy-policy/','Cloudflare privacy information: https://www.cloudflare.com/privacypolicy/','Post for Me privacy information: https://www.postforme.dev','Google privacy information: https://policies.google.com/privacy','Stripe privacy information: https://stripe.com/privacy']},
{title:'Social publishing and access tokens',paragraphs:['Connecting an account authorizes the permissions shown during the platform connection flow. When you publish or schedule a post, Riffi sends its media, captions and destination account identifiers to Post for Me and the selected social platforms. The platforms may make that content public according to your selected settings.','Social tokens for Post for Me connections remain with that provider. Legacy direct connections, where used, store encrypted tokens in Riffi. Disconnecting prevents future use through that connection; it does not remove posts already published or necessarily revoke all permissions at the social platform. You can also revoke access in the platform’s own settings.']},
{title:'Sharing and disclosures',paragraphs:['We share information with service providers to perform the functions above, with social platforms for authorized posting, and when required by applicable law or reasonably necessary to protect accounts and the service. Information may also be transferred as part of a business transaction, subject to applicable privacy obligations. We do not sell your personal information or use it for cross-context behavioral advertising.']},
{title:'Storage, retention and security',paragraphs:['We keep account and workspace records while needed to provide the service. You can remove unused assets and drafts in the app. Contact support@riffi.com to request account deletion or an export. Security, billing, legal or dispute records may need to be retained after a request; backups and third-party records may follow separate retention cycles. We will explain applicable limits when handling your request. We do not promise instant deletion from every backup or connected provider.','Access checks, password hashing, secure session cookies, token protections and temporary signed media links help protect your workspace. No online service is completely secure. Media links used for publishing can be accessed by whoever possesses a valid link until it expires. Do not share those links unnecessarily.']},
{title:'Your choices and privacy rights',paragraphs:['You can edit your profile and business details, remove drafts and assets, disconnect social accounts and request assistance with access, correction, export or deletion at support@riffi.com. We may verify account ownership before acting. Depending on where you live, you may also have rights to object to or restrict processing, withdraw consent, or complain to your local privacy regulator. We respond within applicable legal requirements and do not penalize you for exercising rights.','Where applicable law requires a legal basis, service delivery relies on contractual necessity; security and service operations on legitimate interests; required records on legal obligations; and optional uses requiring permission on consent. Information may be processed in countries different from yours through our providers. Applicable transfer requirements must be respected.']},
{title:'Canadian privacy rights and accountability',paragraphs:['Riffi handles personal information under applicable Canadian privacy law, including the Personal Information Protection and Electronic Documents Act (PIPEDA) where it applies, and applicable provincial requirements. Direct privacy requests and complaints to support@riffi.com, for the person responsible for privacy at Riffi. You may request access to information about you, correction of inaccuracies, an explanation of its use and disclosures, or withdrawal of consent subject to legal or contractual restrictions. Withdrawing information necessary for a feature may prevent us from providing that feature.','We explain relevant purposes when collecting information and obtain consent where required. We do not treat agreement to these terms as blanket consent for unrelated uses. If a privacy issue remains unresolved, you can contact the Office of the Privacy Commissioner of Canada or the applicable provincial privacy commissioner. PIPEDA access requests are generally answered within 30 days, subject to legally permitted extensions and exceptions.','Our providers may process information outside Canada, including in the United States. Information processed abroad may be subject to that jurisdiction’s laws and access by its courts or authorities. We remain accountable for personal information transferred for processing and use appropriate contractual and other safeguards. If a breach triggers notification or reporting obligations under applicable law, we will notify affected people and the relevant authority as required.'],items:['Canadian privacy information and complaint guidance: https://www.priv.gc.ca/en/report-a-concern/guide/']},
{title:'Children and policy changes',paragraphs:['Riffi is intended for adult business users and creators, not children under 18. Do not submit a child’s personal information without appropriate authority. If you believe a child has provided account information, contact support@riffi.com. We may update this policy as the service changes, update the date, and provide additional notice for material changes where required.']}
]},
terms:{title:'Terms and Conditions',summary:'The ground rules for creating, planning and publishing with Riffi.',sections:[
{title:'Using Riffi',paragraphs:['Riffi operates in Canada. These terms govern your use of Riffi. By creating an account or using the service, you agree to these terms and the Acceptable Use Policy. If you use Riffi for an organization, you must have authority to act for it. You must be at least 18 and legally able to enter this agreement. Contact support@riffi.com with questions.']},
{title:'Your account',paragraphs:['Provide accurate account information, protect your sign-in credentials, and authorize only people who should access your business content. You are responsible for actions through your account, except where applicable law provides otherwise. Notify support@riffi.com if you suspect unauthorized access. Google and social sign-in features require their providers’ permissions and terms.']},
{title:'Your content and permissions',paragraphs:['You retain your rights in the business information, prompts and assets you provide. You grant Riffi the limited permission necessary to store, process, transform and transmit that material to provide requested features, including generation and authorized publication. You must have rights to website content, logos, fonts, images, music, voices and likenesses you import or upload. A public URL does not establish ownership or permission.','As between you and Riffi, you may use generated output to the extent permitted by applicable law and provider terms. Output may not be unique or eligible for intellectual-property protection. We do not guarantee exclusivity, ownership rights against third parties, or freedom from infringement. Riffi’s software, branding and interface remain the property of their respective owners.']},
{title:'Review before publishing',paragraphs:['You are responsible for reviewing claims, captions, visual assets, accessibility, disclosures and permissions before publication. AI can produce inaccurate or unsuitable content. Do not treat output as professional legal, financial or medical advice. Obtain consent before using a person’s likeness or voice and disclose sponsored or AI-generated content when required. We do not guarantee reach, sales or engagement.']},
{title:'Scheduling and third-party platforms',paragraphs:['Publishing requires a connected account and platform approval. By scheduling or selecting Publish now, you authorize delivery of that content to the chosen accounts. Check account selection, time and timezone before confirming. Platform outages, permissions, rate limits and processing can delay or prevent publication. A successful submission is not confirmed publication. Multi-platform jobs may succeed for some accounts and fail for others.','You can cancel or change a schedule before publishing begins where the app permits. Once content is submitted, cancellation or removal may need to happen on the social platform. Check platform results before retrying a failed or uncertain job to avoid duplicates. Disconnecting does not remove existing posts.']},
{title:'Plans, payment and cancellation',paragraphs:['Current pricing and usage allowances are shown in the app and at checkout. A paid subscription is offered only when payment processing is enabled. The billing interval, renewal price and any trial conditions are disclosed before purchase. Unless canceled, a recurring subscription renews as described at checkout. Applicable taxes may be added.','Cancel through the billing portal when available, or contact support@riffi.com for help. Deleting a draft, disconnecting a social account, or stopping use does not cancel a subscription. Cancellation stops future renewal according to the provider’s billing rules. Refund requests are handled under our Refund and Cancellation Policy and applicable consumer law. Changes to recurring prices will be communicated where required before they apply.']},
{title:'Availability, suspension and termination',paragraphs:['Features depend on configuration, plans and external providers. We may maintain or change the service and may restrict accounts for violations, security risks or legal requirements. Where practical, we provide notice and an opportunity to resolve an issue. You may stop using the service and request deletion at support@riffi.com. Suspension does not waive statutory refund rights or required access to your information.']},
{title:'Responsibilities and disputes',paragraphs:['To the extent permitted by law, Riffi is provided as available without guarantees of uninterrupted service, error-free output or fitness for a particular outcome. Nothing in these terms excludes rights or liability that cannot legally be excluded, including mandatory consumer protections.','Contact support@riffi.com first so we can try to resolve a dispute. These terms do not impose mandatory arbitration. Applicable Canadian law and any mandatory protections in your place of residence determine your rights and available remedies. These terms do not restrict a consumer’s right to bring a claim in a court that has jurisdiction. If part of these terms is unenforceable, the remaining provisions continue to apply to the extent permitted.']},
{title:'Changes to these terms',paragraphs:['We may update these terms as Riffi changes. We update the date and provide notice of material changes where required. Changes do not remove rights that arose before the change or override applicable law.']}
]},
cookies:{title:'Cookie and Storage Policy',summary:'The browser storage Riffi uses to keep your session and workspace working.',sections:[
{title:'Necessary cookies',paragraphs:['Riffi uses a secure, HTTP-only session cookie to keep you signed in. Its current maximum lifetime is 30 days; logging out ends the active session. A temporary Google sign-in state cookie lasts up to 10 minutes to help verify the sign-in callback. Browser and hosting services may also use necessary security cookies.']},
{title:'Browser storage',paragraphs:['Session storage remembers a website entered during signup and the selected business workspace. This helps onboarding and navigation continue without repeating inputs. These values are browser state, not a replacement for your saved account records.']},
{title:'Analytics and advertising',paragraphs:['The current app does not install advertising or behavioral tracking cookies. Hosting services process operational information to deliver and secure the app. Connected providers’ pages and embedded or external services may have their own cookies and policies. If Riffi introduces optional tracking requiring consent, it must explain that use and obtain the required choices before enabling it.']},
{title:'Your controls',paragraphs:['You can clear or block cookies and browser storage in browser settings. Blocking necessary cookies can prevent sign-in or disrupt the workspace. Logging out removes the active sign-in cookie. Clearing browser storage does not delete server-side accounts, content or billing records. For questions or deletion assistance, email support@riffi.com.']}
]},
'acceptable-use':{title:'Acceptable Use Policy',summary:'Create useful content, respect people, and protect the platforms we share.',sections:[
{title:'Create responsibly',paragraphs:['Use Riffi only for lawful content and authorized accounts. Respect platform rules, other people’s rights and the audience you are reaching. You are responsible for permissions and disclosures, including when using public website assets.']},
{title:'Prohibited use',paragraphs:['Do not use Riffi for:'],items:['Illegal activity, fraud, scams, deceptive advertising or false product claims.','Harassment, threats, hateful abuse, exploitation, or sexual content involving minors.','Impersonation or non-consensual use of someone’s likeness, voice or private information.','Copyright, trademark, privacy or other rights violations.','Spam, purchased or stolen accounts, unauthorized posting, or evasion of platform restrictions.','Malware, credential theft, attempts to access another workspace, or disruption of the service.','Misleading endorsements, fabricated testimonials, or hiding required sponsorship and AI disclosures.']},
{title:'Enforcement and reports',paragraphs:['We may investigate reports, restrict affected features or suspend accounts where necessary. Action should be proportionate to the risk and applicable law. To report misuse or request review of an account restriction, email support@riffi.com with relevant account or post identifiers and a description. Do not send passwords or private access tokens.']}
]},
refunds:{title:'Refund and Cancellation Policy',summary:'Clear steps for subscription changes, billing questions and refund requests.',sections:[
{title:'Before you purchase',paragraphs:['Review the plan, price, billing interval, usage allowances and renewal terms shown at checkout. A free workspace does not itself charge a payment method. Paid checkout is available only when the payment provider is configured. We do not promise a refund window or money-back guarantee that has not been displayed with your purchase.']},
{title:'Canceling a subscription',paragraphs:['Use the billing portal in your workspace when available. If you cannot access it, email support@riffi.com from the account email with your cancellation request. Cancellation stops future renewal according to your subscription’s billing terms. Review the confirmation for the effective date and access period. Deleting content, disconnecting accounts or requesting account deletion does not automatically cancel billing.']},
{title:'Refund requests',paragraphs:['Email support@riffi.com with the account email, invoice identifier, charge date and reason for the request. We review duplicate charges, billing mistakes, unauthorized charges and other requests based on the purchase terms and applicable law. An unused allowance does not automatically create a refund entitlement. Any approved refund is returned through the original payment provider where possible, subject to its processing times.','Your mandatory consumer rights take precedence over this policy. We do not exclude refunds, withdrawal rights or other remedies that applicable law requires. No fixed response or refund processing time is guaranteed.']},
{title:'Billing problems',paragraphs:['If a payment looks unfamiliar, contact support@riffi.com promptly. Include only the information needed to locate the charge. Never email a full card number, security code, password or access token.']}
]},
'data-deletion':{title:'Data Access and Deletion',summary:'How to request a copy of your information or close your Riffi account.',sections:[
{title:'Make a request',paragraphs:['Email support@riffi.com from the email associated with your account. Use “Data export”, “Data correction” or “Account deletion” in the subject, and explain which account, business or information the request concerns. We may ask for additional proof of ownership. Never send a password or social access token.']},
{title:'Before deleting your account',paragraphs:['Save any content you want to keep, cancel paid subscriptions through the billing portal or with support, and disconnect social accounts. Account deletion can remove access to brand profiles, uploaded assets, drafts and schedules. Ask support to confirm the scope before deletion is carried out.']},
{title:'What deletion covers',paragraphs:['After ownership verification, we assess the request and remove or de-identify information that is no longer needed, subject to applicable legal requirements. Billing, fraud-prevention, dispute or legal records may need to be retained. Backups and service-provider records may follow separate retention cycles. We explain any applicable exceptions rather than promising immediate removal from every system.']},
{title:'Published content and provider data',paragraphs:['Deleting a Riffi account does not delete posts already published on TikTok, Instagram, Facebook, Threads or other platforms. Remove those posts and revoke app permissions using the platform’s own controls. Provider-side information is also subject to the provider’s privacy policy. We can help identify the relevant service.']},
{title:'Requests and timing',paragraphs:['We handle requests within applicable legal time limits and may explain verification requirements, scope limitations or permitted extensions. Contact support@riffi.com for updates or to correct a request.']}
]},
support:{title:'Support & Contact',summary:'A little help from the people behind your brand’s buddy.',sections:[
{title:'Contact Riffi',paragraphs:['For account, content, publishing, billing, privacy or security assistance, email support@riffi.com. This is the contact address for all Riffi policies. Support is handled by email; we do not currently promise 24/7 coverage or a fixed response time.']},
{title:'Help us find the issue',paragraphs:['Include your account email, business name, what you were trying to do, the error shown and the approximate time with timezone. For publishing issues, include the platform and relevant job or post identifier. Screenshots can help; hide confidential content before sending. Never send passwords, full payment card details, API keys or social access tokens.']},
{title:'Sign-in and account help',paragraphs:['Use email and password on the sign-in page. Google sign-in becomes available when configured. Existing password users can link a matching Google account from Profile after signing in. Password reset and verification emails depend on email delivery being enabled. If a link does not arrive or the feature is unavailable, contact support@riffi.com.']},
{title:'Brand imports and content',paragraphs:['Start with a public website or product URL. Some websites block automated access or do not expose all brand assets. You can review imported details, correct branding and add missing assets manually. Check generated captions, imagery and product claims before posting. Video generation depends on an enabled video provider.']},
{title:'Scheduling and publishing help',paragraphs:['Check the selected accounts, connection status, final slide export, timezone and TikTok privacy options. The calendar confirms publication using platform results. A job can succeed for some accounts and fail for others. If a submission is uncertain, check the social platform before retrying to avoid a duplicate. Disconnect and reconnect an expired or revoked account if needed.']},
{title:'Billing, privacy and security',paragraphs:['Manage subscriptions through the billing portal when enabled, or contact support@riffi.com for assistance. Send data access, correction or deletion requests from your account email. For a suspected security issue, include a clear description and affected feature, but avoid accessing another person’s data or sending secrets.']}
]}
};
export const policyLinks=[['privacy','Privacy'],['terms','Terms'],['cookies','Cookies'],['acceptable-use','Acceptable use'],['refunds','Refunds & cancellation'],['data-deletion','Data requests'],['support','Support']] as const;
