import {presentation,contrastColor} from './slide-design';import {layoutSlide} from './slide-layout';
import {loadBrandFonts} from './brand-fonts';
import type {Slide,Business} from './types';
export function templateColors(template:string,kit:any){if(template==='Dark Tech')return {bg:'#202029',fg:'#ffffff',accent:kit.accent_color||'#d9ef9b'};if(template==='Viral Bold')return {bg:kit.accent_color||'#d9ef9b',fg:'#24282a',accent:kit.primary_color||'#7047eb'};if(template==='Lifestyle')return {bg:'#edcfe0',fg:'#512b46',accent:kit.primary_color||'#7047eb'};if(template==='Creator UGC')return {bg:'#ede6db',fg:'#392d25',accent:kit.primary_color||'#7047eb'};if(template==='Product Demo'||template==='SaaS')return {bg:kit.primary_color||'#7047eb',fg:'#ffffff',accent:kit.accent_color||'#d9ef9b'};return {bg:'#f7f4ee',fg:'#28242d',accent:kit.primary_color||'#7047eb'}}
function lines(ctx:CanvasRenderingContext2D,text:string,width:number){const out:string[]=[];for(const paragraph of text.split('\n')){let line='';for(const word of paragraph.split(/\s+/)){if(ctx.measureText((line?line+' ':'')+word).width>width&&line){out.push(line);line=word}else line+=(line?' ':'')+word}out.push(line)}return out}
async function loadImage(url:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('A slide image could not load. Replace it or retry export.'));image.src=url})}
export async function renderSlide(slide:Slide,business:Business,index:number,total:number):Promise<Blob>{
 await loadBrandFonts(business.kit);const w=1080,h=slide.canvas.height,canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d')!;const colors=templateColors(slide.template_id,business.kit),p=presentation(slide);ctx.fillStyle=slide.background_color||colors.bg;ctx.fillRect(0,0,w,h);
 if(p.photo){const image=await loadImage('/api/assets/'+slide.asset_id+'/file');const boxHeight=slide.layout==='split'?h*.43:h,top=slide.layout==='split'?h-boxHeight:0;const scale=Math.max(w/image.width,boxHeight/image.height)*(slide.image_zoom||1);ctx.save();ctx.beginPath();ctx.rect(0,top,w,boxHeight);ctx.clip();ctx.drawImage(image,(w-image.width*scale)*(slide.crop_x/100),top+(boxHeight-image.height*scale)*(slide.crop_y/100),image.width*scale,image.height*scale);ctx.restore();if(p.shade>0){ctx.fillStyle=`rgba(0,0,0,${p.shade})`;ctx.fillRect(0,0,w,h)}}
 const blocks=layoutSlide(slide,ctx);
 for(const block of blocks){ctx.font=`${block.weight} ${block.size}px "${block.font}"`;ctx.textBaseline='top';ctx.textAlign='left';ctx.lineJoin='round';ctx.lineWidth=block.strokeWidth;ctx.strokeStyle=block.stroke;
 for(let i=0;i<block.lines.length;i++){const width=block.lineWidths[i],x=block.align==='left'?block.x-block.width/2+20:block.align==='right'?block.x+block.width/2-width-20:block.x-width/2,y=block.y+i*block.lineHeight;
 if(block.style==='boxed'){ctx.fillStyle=block.background;ctx.beginPath();ctx.roundRect(x-20,y-2,width+40,block.lineHeight+2,12);ctx.fill()}ctx.fillStyle=block.color;if(block.style==='outlined'&&block.strokeWidth)ctx.strokeText(block.lines[i],x,y);ctx.fillText(block.lines[i],x,y)}}
 if(slide.show_brand&&business.kit.logo_asset_id){const logo=await loadImage('/api/assets/'+business.kit.logo_asset_id+'/file');const scale=Math.min(75/logo.width,75/logo.height);ctx.drawImage(logo,w-80-75,60,logo.width*scale,logo.height*scale)}
 if(slide.show_brand){ctx.font='700 30px "TikTok Sans"';ctx.fillStyle=blocks[0]?.color||'#111';ctx.fillText(business.name,80,60)}ctx.font='600 24px "TikTok Sans"';ctx.textAlign='right';ctx.fillStyle=blocks[0]?.color||'#111';ctx.globalAlpha=.65;ctx.fillText(`${index+1}/${total}`,w-100,h-170);ctx.globalAlpha=1;
 return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Could not render this slide.')),'image/jpeg',.93))
}
export function download(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)}
const crcTable=Array.from({length:256},(_,i)=>{let c=i;for(let j=0;j<8;j++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0});const crc=(bytes:Uint8Array)=>{let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0};
export async function zip(files:{name:string;blob:Blob}[]){const encoder=new TextEncoder(),parts:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;for(const f of files){const name=encoder.encode(f.name),data=new Uint8Array(await f.blob.arrayBuffer()),checksum=crc(data);const header=new Uint8Array(30+name.length),v=new DataView(header.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,checksum,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);header.set(name,30);parts.push(header,data);const c=new Uint8Array(46+name.length),cv=new DataView(c.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint32(16,checksum,true);cv.setUint32(20,data.length,true);cv.setUint32(24,data.length,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);c.set(name,46);central.push(c);offset+=header.length+data.length}const size=central.reduce((s,c)=>s+c.length,0),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,files.length,true);ev.setUint16(10,files.length,true);ev.setUint32(12,size,true);ev.setUint32(16,offset,true);return new Blob([...parts,...central,end] as BlobPart[],{type:'application/zip'})}
