import {presentation,contrastColor} from './slide-design';
import {loadBrandFonts} from './brand-fonts';
import type {Slide,Business} from './types';
export function templateColors(template:string,kit:any){if(template==='Dark Tech')return {bg:'#202029',fg:'#ffffff',accent:kit.accent_color||'#d9ef9b'};if(template==='Viral Bold')return {bg:kit.accent_color||'#d9ef9b',fg:'#24282a',accent:kit.primary_color||'#7047eb'};if(template==='Lifestyle')return {bg:'#edcfe0',fg:'#512b46',accent:kit.primary_color||'#7047eb'};if(template==='Creator UGC')return {bg:'#ede6db',fg:'#392d25',accent:kit.primary_color||'#7047eb'};if(template==='Product Demo'||template==='SaaS')return {bg:kit.primary_color||'#7047eb',fg:'#ffffff',accent:kit.accent_color||'#d9ef9b'};return {bg:'#f7f4ee',fg:'#28242d',accent:kit.primary_color||'#7047eb'}}
function lines(ctx:CanvasRenderingContext2D,text:string,width:number){const out:string[]=[];for(const paragraph of text.split('\n')){let line='';for(const word of paragraph.split(/\s+/)){if(ctx.measureText((line?line+' ':'')+word).width>width&&line){out.push(line);line=word}else line+=(line?' ':'')+word}out.push(line)}return out}
async function loadImage(url:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('A slide image could not load. Replace it or retry export.'));image.src=url})}
export async function renderSlide(slide:Slide,business:Business,index:number,total:number):Promise<Blob>{
 await loadBrandFonts(business.kit);const w=1080,h=slide.canvas.height,canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d')!;const colors=templateColors(slide.template_id,business.kit),p=presentation(slide);ctx.fillStyle=colors.bg;ctx.fillRect(0,0,w,h);
 if(p.photo){const image=await loadImage('/api/assets/'+slide.asset_id+'/file');const boxHeight=slide.layout==='split'?h*.43:h,top=slide.layout==='split'?h-boxHeight:0;const scale=Math.max(w/image.width,boxHeight/image.height);ctx.drawImage(image,(w-image.width*scale)*(slide.crop_x/100),top+(boxHeight-image.height*scale)*(slide.crop_y/100),image.width*scale,image.height*scale);if(p.shade>0){ctx.fillStyle=`rgba(0,0,0,${p.shade})`;ctx.fillRect(0,0,w,h)}}
 const color=slide.text_color||(p.photo&&slide.layout!=='split'?'#ffffff':contrastColor(colors.bg));const font=p.photo?'Arial':business.kit.heading_font||'Arial';const margin=85,maxWidth=w-margin*2;let size=p.headlineSize*w/100;let headline:string[]=[];const bodySize=p.bodySize*w/100;ctx.font=`${bodySize}px "${business.kit.body_font||'Arial'}"`;const body=p.showBody&&slide.supporting_text?lines(ctx,slide.supporting_text,maxWidth):[];const bodyHeight=body.length*bodySize*1.35+(body.length?size*.6:0);const maxHeight=p.position==='middle'?h*.67:h*.57;
 do{ctx.font=`${p.weight} ${size}px "${font}"`;headline=lines(ctx,slide.headline,maxWidth);if(headline.length*size*(p.photo?1.13:1.02)+bodyHeight<=maxHeight||size<=52)break;size-=3}while(true);
 const lineHeight=size*(p.photo?1.13:1.02),totalHeight=headline.length*lineHeight+bodyHeight;let y=p.position==='top'?h*.16:p.position==='bottom'?h*.79-totalHeight:(h-totalHeight)/2;if(slide.layout==='split')y=140;
 ctx.textAlign=slide.align;ctx.textBaseline='top';const x=slide.align==='center'?w/2:slide.align==='right'?w-margin:margin;ctx.fillStyle=color;ctx.lineJoin='round';ctx.lineWidth=p.photo?10.8:14;ctx.strokeStyle='#111';
 if(p.style==='boxed'){const widths=headline.map(l=>ctx.measureText(l).width);ctx.fillStyle='#ffffff';const boxWidth=Math.max(...widths)+48;const left=slide.align==='center'?(w-boxWidth)/2:slide.align==='right'?w-margin-boxWidth:margin-24;ctx.fillRect(left,y-22,boxWidth,headline.length*lineHeight+38);ctx.fillStyle='#111'}
 for(const line of headline){if(p.style==='outlined')ctx.strokeText(line,x,y);ctx.fillText(line,x,y);y+=lineHeight}if(body.length){y+=size*.6;ctx.font=`${bodySize}px "${business.kit.body_font||'Arial'}"`;if(p.style==='boxed'){const boxWidth=Math.max(...body.map(l=>ctx.measureText(l).width))+48;const left=slide.align==='center'?(w-boxWidth)/2:slide.align==='right'?w-margin-boxWidth:margin-24;ctx.fillStyle='#fff';ctx.fillRect(left,y-12,boxWidth,body.length*bodySize*1.35+24)}ctx.fillStyle=p.style==='boxed'?'#111':color;for(const line of body){if(p.style==='outlined')ctx.strokeText(line,x,y);ctx.fillText(line,x,y);y+=bodySize*1.35}}
 if(p.showBrand){ctx.fillStyle=color;ctx.font='700 32px Arial';ctx.textAlign='left';ctx.fillText(business.name,85,75);if(business.kit.logo_asset_id){try{const logo=await loadImage('/api/assets/'+business.kit.logo_asset_id+'/file');const scale=75/Math.max(logo.width,logo.height);ctx.drawImage(logo,w-160,65,logo.width*scale,logo.height*scale)}catch{}}}
 if(slide.cta){ctx.textAlign=slide.align;ctx.font='800 42px Arial';ctx.fillStyle=color;const ctaLines=lines(ctx,slide.cta,maxWidth);let cy=h*.86;for(const line of ctaLines){if(p.photo){ctx.lineWidth=8;ctx.strokeText(line,x,cy)}ctx.fillText(line,x,cy);cy+=52}}
 ctx.textAlign='right';ctx.font='700 26px Arial';ctx.fillStyle=color;ctx.globalAlpha=.7;ctx.fillText(`${index+1}/${total}`,w-85,h-90);ctx.globalAlpha=1;
 return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Could not render this slide.')),'image/jpeg',.93))
}
export function download(blob:Blob,name:string){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)}
const crcTable=Array.from({length:256},(_,i)=>{let c=i;for(let j=0;j<8;j++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0});const crc=(bytes:Uint8Array)=>{let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0};
export async function zip(files:{name:string;blob:Blob}[]){const encoder=new TextEncoder(),parts:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;for(const f of files){const name=encoder.encode(f.name),data=new Uint8Array(await f.blob.arrayBuffer()),checksum=crc(data);const header=new Uint8Array(30+name.length),v=new DataView(header.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint32(14,checksum,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);header.set(name,30);parts.push(header,data);const c=new Uint8Array(46+name.length),cv=new DataView(c.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint32(16,checksum,true);cv.setUint32(20,data.length,true);cv.setUint32(24,data.length,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);c.set(name,46);central.push(c);offset+=header.length+data.length}const size=central.reduce((s,c)=>s+c.length,0),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,files.length,true);ev.setUint16(10,files.length,true);ev.setUint32(12,size,true);ev.setUint32(16,offset,true);return new Blob([...parts,...central,end] as BlobPart[],{type:'application/zip'})}
