import type {Slide} from './types';
export const SLIDE_FONTS=['TikTok Sans','Arial','Helvetica','Georgia','Verdana'] as const;
export function wrapText(text:string,width:number,measure:(text:string)=>number){const lines:string[]=[];for(const p of text.split('\n')){let line='';for(const word of p.split(/\s+/).filter(Boolean)){if(measure(word)>width){if(line){lines.push(line);line=''}let part='';for(const c of word){if(measure(part+c)>width&&part){lines.push(part);part=''}part+=c}line=part;continue}if(line&&measure(line+' '+word)>width){lines.push(line);line=word}else line+=(line?' ':'')+word}if(line)lines.push(line)}return lines}
export type TextBlock={id:string;lines:string[];size:number;font:string;weight:string;lineHeight:number;x:number;y:number;width:number;height:number;color:string;style:string;background:string;stroke:string;strokeWidth:number;align:Slide['align'];lineWidths:number[]};
export function layoutSlide(slide:Slide,ctx:CanvasRenderingContext2D){const photo=!!slide.asset_id,h=slide.canvas.height,style=slide.text_style||(photo?'boxed':'clean'),font=slide.font_family||'TikTok Sans',weight=slide.text_weight||'700',color=style==='boxed'?(slide.text_color&&!(slide.text_color==='#ffffff'&&!slide.font_family)?slide.text_color:'#111111'):(slide.text_color||(photo?'#ffffff':'#202029')),width=1080*(slide.text_width||82)/100,pad=style==='boxed'?20:0;const pos=slide.text_position||(photo?'top':'middle');const output:TextBlock[]=[];
function block(id:string,text:string,size:number,y?:number,x=48){let lines:string[]=[];let widths:number[]=[];const limit=Math.min(h*.28,540);do{ctx.font=`${weight} ${size}px "${font}"`;lines=wrapText(text,width-pad*2,t=>ctx.measureText(t).width);widths=lines.map(t=>ctx.measureText(t).width);if(lines.length*size*1.18<=limit||size<=30)break;size-=2}while(true);const lineHeight=size*1.18,height=lines.length*lineHeight+pad*.8,bw=Math.max(0,...widths)+pad*2;const px=Math.max(bw/2+60,Math.min(1080-bw/2-100,x*10.8));const py=Math.max(h*.1,Math.min(h*.8-height,(y??30)*h/100));const b={id,lines,size,font,weight,lineHeight,x:px,y:py,width:bw,height,color,style,background:slide.text_background||'#ffffff',stroke:slide.stroke_color||'#111111',strokeWidth:slide.stroke_width??(style==='outlined'?6:0),align:slide.align,lineWidths:widths};output.push(b);return b}
const headline=block('headline',slide.headline,(photo?64:96)*slide.font_size,slide.headline_y??(pos==='top'?17:pos==='bottom'?57:31),slide.headline_x??48);
if((slide.show_body??true)&&slide.supporting_text){const body=block('body',slide.supporting_text,(photo?58:54)*(slide.body_size||1),slide.body_y??((headline.y+headline.height+65)/h*100),slide.body_x??48);if(slide.body_y===undefined&&body.y<headline.y+headline.height+48)headline.y=Math.max(h*.1,body.y-headline.height-48)}
if(slide.cta)block('cta',slide.cta,42,slide.cta_y??72,slide.cta_x??48);
for(const extra of slide.extra_text||[])block(extra.id,extra.text,60*(extra.size||1),extra.y,extra.x);
return output}
